-- DB作成
DROP DATABASE IF EXISTS `flask_login_app_db`;
CREATE DATABASE `flask_login_app_db`;

-- DB切り替え
USE `flask_login_app_db`;

-- DBを操作するユーザーの作成
CREATE USER 'flask_login_app'@'%' IDENTIFIED BY 'flask_login_app';
GRANT USAGE ON *.* TO 'flask_login_app'@'%';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `flask\_login\_app\_db`.* TO 'flask_login_app'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- テーブル作成
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`email` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`password` VARCHAR(255) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
